version: "3"

# volumes:
#     app-data:
#       driver: local

networks:
  internal:
    external: false

services:
    app:
        image: project_tides:0.1.0
        build:
            context: .
        environment:
            - SECRET_KEY_BASE=${SECRET_KEY_BASE}
            - DATABASE_DB=${DATABASE_DB}
            - DATABASE_HOST=db
        ports:
            - 80:4000
        networks:
            - internal
        depends_on: 
            - db
    db:
        image: postgres:10-alpine
        volumes:
            - ./docker-volumes/postgresql:/var/lib/postgresql
            - ./build_scripts/pg:/docker-entrypoint-initdb.d
        environment:
            # - POSTGRES_DB=${DATABASE_DB}
            - POSTGRES_USER=${DATABASE_USER}
            - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
            - POSTGRES_MULTIPLE_DATABASES=${POSTGRES_MULTIPLE_DATABASES}
        networks:
            - internal

