version: "3"

services:
  db:
    image: postgres:10-alpine
    ports:
      - 5677:5432
    volumes:
      - ./docker-volumes/postgresql:/var/lib/postgresql
    environment:
      - POSTGRES_USER=user1
      - POSTGRES_PASSWORD=pass1
      - POSTGRES_DB=main_db

